"""Initial migration

Revision ID: 2c5589a68ebf
Revises: 
Create Date: 2026-07-15 12:31:54.975124

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5589a68ebf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('github_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('github_access_token', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('repositories',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('github_repo_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_login', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clone_url', sa.Text(), nullable=False),
    sa.Column('ssh_url', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.String(length=50), nullable=True),
    sa.Column('index_status', sa.String(length=20), nullable=False),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_functions', sa.Integer(), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('coverage_percentage', sa.Float(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('github_app_installation_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_created_at'), 'repositories', ['created_at'], unique=False)
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_table('bug_history',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('pr_number', sa.String(length=10), nullable=True),
    sa.Column('module_path', sa.Text(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('bug_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('fix_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('qdrant_embedding_id', sa.String(length=100), nullable=True),
    sa.Column('is_production_incident', sa.String(length=5), nullable=False),
    sa.Column('incident_date', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_history_bug_type'), 'bug_history', ['bug_type'], unique=False)
    op.create_index(op.f('ix_bug_history_commit_sha'), 'bug_history', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_bug_history_created_at'), 'bug_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_bug_history_id'), 'bug_history', ['id'], unique=False)
    op.create_index(op.f('ix_bug_history_module_path'), 'bug_history', ['module_path'], unique=False)
    op.create_index(op.f('ix_bug_history_repository_id'), 'bug_history', ['repository_id'], unique=False)
    op.create_index(op.f('ix_bug_history_severity'), 'bug_history', ['severity'], unique=False)
    op.create_table('commits',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('short_sha', sa.String(length=7), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('author_github_username', sa.String(length=100), nullable=True),
    sa.Column('committed_at', sa.String(length=50), nullable=False),
    sa.Column('parents', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_committed_at'), 'commits', ['committed_at'], unique=False)
    op.create_index(op.f('ix_commits_created_at'), 'commits', ['created_at'], unique=False)
    op.create_index(op.f('ix_commits_id'), 'commits', ['id'], unique=False)
    op.create_index(op.f('ix_commits_repository_id'), 'commits', ['repository_id'], unique=False)
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=False)
    op.create_table('dependency_graph',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('source_node', sa.Text(), nullable=False),
    sa.Column('target_node', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('edge_type', sa.String(length=20), nullable=False),
    sa.Column('line_number', sa.String(length=10), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_graph_created_at'), 'dependency_graph', ['created_at'], unique=False)
    op.create_index(op.f('ix_dependency_graph_edge_type'), 'dependency_graph', ['edge_type'], unique=False)
    op.create_index(op.f('ix_dependency_graph_id'), 'dependency_graph', ['id'], unique=False)
    op.create_index(op.f('ix_dependency_graph_repository_id'), 'dependency_graph', ['repository_id'], unique=False)
    op.create_index(op.f('ix_dependency_graph_source_node'), 'dependency_graph', ['source_node'], unique=False)
    op.create_index(op.f('ix_dependency_graph_target_node'), 'dependency_graph', ['target_node'], unique=False)
    op.create_table('pull_requests',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('github_pr_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('head_branch', sa.String(length=255), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=False),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('affected_modules', sa.Text(), nullable=True),
    sa.Column('coverage_before', sa.Float(), nullable=True),
    sa.Column('coverage_after', sa.Float(), nullable=True),
    sa.Column('coverage_delta', sa.Float(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_removed', sa.Integer(), nullable=False),
    sa.Column('github_review_id', sa.String(length=50), nullable=True),
    sa.Column('github_check_run_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_created_at'), 'pull_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_pull_requests_github_pr_id'), 'pull_requests', ['github_pr_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_id'), 'pull_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pull_requests_pr_number'), 'pull_requests', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_state'), 'pull_requests', ['state'], unique=False)
    op.create_table('repository_files',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ast_hash', sa.String(length=64), nullable=True),
    sa.Column('last_parsed_at', sa.String(length=50), nullable=True),
    sa.Column('is_test_file', sa.Boolean(), nullable=False),
    sa.Column('functions', sa.Text(), nullable=True),
    sa.Column('classes', sa.Text(), nullable=True),
    sa.Column('imports', sa.Text(), nullable=True),
    sa.Column('exports', sa.Text(), nullable=True),
    sa.Column('routes', sa.Text(), nullable=True),
    sa.Column('qdrant_chunk_ids', sa.Text(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_files_created_at'), 'repository_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_repository_files_id'), 'repository_files', ['id'], unique=False)
    op.create_index(op.f('ix_repository_files_is_test_file'), 'repository_files', ['is_test_file'], unique=False)
    op.create_index(op.f('ix_repository_files_language'), 'repository_files', ['language'], unique=False)
    op.create_index(op.f('ix_repository_files_repository_id'), 'repository_files', ['repository_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('pull_request_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('finished_at', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_pull_request_id'), 'agent_runs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('ai_logs',
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('success', sa.String(length=5), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pr_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_agent_name'), 'ai_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_ai_logs_created_at'), 'ai_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_logs_model'), 'ai_logs', ['model'], unique=False)
    op.create_index(op.f('ix_ai_logs_pr_id'), 'ai_logs', ['pr_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_repository_id'), 'ai_logs', ['repository_id'], unique=False)
    op.create_table('generated_tests',
    sa.Column('pull_request_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('test_file_path', sa.Text(), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('test_framework', sa.String(length=50), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_result', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('generation_prompt_tokens', sa.String(length=10), nullable=True),
    sa.Column('generation_completion_tokens', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_tests_created_at'), 'generated_tests', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_tests_id'), 'generated_tests', ['id'], unique=False)
    op.create_index(op.f('ix_generated_tests_pull_request_id'), 'generated_tests', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_generated_tests_repository_id'), 'generated_tests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_generated_tests_status'), 'generated_tests', ['status'], unique=False)
    op.create_table('review_comments',
    sa.Column('pull_request_id', sa.String(length=36), nullable=False),
    sa.Column('github_comment_id', sa.String(length=50), nullable=True),
    sa.Column('github_review_id', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('is_posted', sa.String(length=5), nullable=False),
    sa.Column('posted_at', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.String(length=10), nullable=True),
    sa.Column('completion_tokens', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_created_at'), 'review_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_comments_id'), 'review_comments', ['id'], unique=False)
    op.create_index(op.f('ix_review_comments_pull_request_id'), 'review_comments', ['pull_request_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('pull_request_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('runner', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('finished_at', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('skipped_tests', sa.Integer(), nullable=False),
    sa.Column('error_tests', sa.Integer(), nullable=False),
    sa.Column('coverage_percentage', sa.Float(), nullable=True),
    sa.Column('coverage_report', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('working_directory', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_created_at'), 'test_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_test_runs_pull_request_id'), 'test_runs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_test_runs_repository_id'), 'test_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_table('test_results',
    sa.Column('test_run_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=False),
    sa.Column('test_file', sa.Text(), nullable=True),
    sa.Column('test_class', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('failure_type', sa.String(length=255), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_created_at'), 'test_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_status'), 'test_results', ['status'], unique=False)
    op.create_index(op.f('ix_test_results_test_name'), 'test_results', ['test_name'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_name'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_status'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_created_at'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_repository_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_pull_request_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_created_at'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_review_comments_pull_request_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_created_at'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_generated_tests_status'), table_name='generated_tests')
    op.drop_index(op.f('ix_generated_tests_repository_id'), table_name='generated_tests')
    op.drop_index(op.f('ix_generated_tests_pull_request_id'), table_name='generated_tests')
    op.drop_index(op.f('ix_generated_tests_id'), table_name='generated_tests')
    op.drop_index(op.f('ix_generated_tests_created_at'), table_name='generated_tests')
    op.drop_table('generated_tests')
    op.drop_index(op.f('ix_ai_logs_repository_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_pr_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_model'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_created_at'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_agent_name'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_pull_request_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_repository_files_repository_id'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_language'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_is_test_file'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_id'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_created_at'), table_name='repository_files')
    op.drop_table('repository_files')
    op.drop_index(op.f('ix_pull_requests_state'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_pr_number'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_github_pr_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_created_at'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_dependency_graph_target_node'), table_name='dependency_graph')
    op.drop_index(op.f('ix_dependency_graph_source_node'), table_name='dependency_graph')
    op.drop_index(op.f('ix_dependency_graph_repository_id'), table_name='dependency_graph')
    op.drop_index(op.f('ix_dependency_graph_id'), table_name='dependency_graph')
    op.drop_index(op.f('ix_dependency_graph_edge_type'), table_name='dependency_graph')
    op.drop_index(op.f('ix_dependency_graph_created_at'), table_name='dependency_graph')
    op.drop_table('dependency_graph')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_index(op.f('ix_commits_repository_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_created_at'), table_name='commits')
    op.drop_index(op.f('ix_commits_committed_at'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_bug_history_severity'), table_name='bug_history')
    op.drop_index(op.f('ix_bug_history_repository_id'), table_name='bug_history')
    op.drop_index(op.f('ix_bug_history_module_path'), table_name='bug_history')
    op.drop_index(op.f('ix_bug_history_id'), table_name='bug_history')
    op.drop_index(op.f('ix_bug_history_created_at'), table_name='bug_history')
    op.drop_index(op.f('ix_bug_history_commit_sha'), table_name='bug_history')
    op.drop_index(op.f('ix_bug_history_bug_type'), table_name='bug_history')
    op.drop_table('bug_history')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_created_at'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
